# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: jenkinsdashboard_development
  pool: 5
  username: alexfish
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: jenkinsdashboard_test
  pool: 5
  username: alexfish
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: jenkinsdashboard_prod
  pool: 5
  username:
  password:
